services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vllm_fastapi_service
    ports:
      - "8001:8001"
    volumes:
      - c:\hackathon\results\:/app/files   # Папка для входных файлов
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Количество GPU (можно указать "all" для всех доступных)
              capabilities: [gpu] # Тип ресурсов: GPU